package qa.automation.enums;

public enum Property {
    TIMEOUT_MS,
    SAVE_TEST_DATA_TO_BLOB_STORAGE,
    REPETITION,
    PERFORMANCE,
    DEBUG_LOGGING,
    HOOKS_ENABLED,
    HEADLESS,
    MAIN_PAGE_WIDTH,
    MAIN_PAGE_HEIGHT,
    TRADE_PAGE_WIDTH,
    TRADE_PAGE_HEIGHT,
    SAVE_AUDIT_TRACING_ON_SUCCESS,
    SAVE_AUDIT_TRACING_ON_FAILURE,
    SAVE_POD_LOGS_ON_FAILURE,
    SAVE_TEST_DATA_ON_SUCCESS,
    SAVE_TEST_DATA_ON_FAILURE,
    SAVE_FE_TRACING_ON_SUCCESS,
    SAVE_FE_TRACING_ON_FAILURE,
    ENABLED_VIDEO_RECORDING,
    CLIENT_SECRET,
}
