baseUrl=https://www.saucedemo.com/
headless=false
trace=true
screenshotDir=reports/screenshots
reportsDir=reports
redis.host=redis_host
redis.port=port_num
redis.password=xxxxxxxxxxxxxx
redis.defaultTtlSeconds=1800
azure.tables.connectionString=DefaultEndpointsProtocol=https;AccountName=xxxxxxx;AccountKey=xxxxxxxxxxxxxx;EndpointSuffix=core.windows.net
azure.tables.table=xxxxxxxxxx
apiConfig.baseUrl=https://xxxxxxxxx.com
api.auth.bearerToken=
oracle.db.url = jdbc:oracle:thin:@//xxxxxxxx
oracle.db.user= xxxxx
oracle.db.password=xxxxxx
parallel.threads=4
testAccount01@orgname.com=password01
testAccount02@orgname.com=password02